# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Ratioscore
tagline:          'Just Interval Tool'
description:      'Just Interval Tool'
url:              https://ratioscore.humdrum.org
baseurl:          /

paginate:         5

# Stylings

#content_background:                "#b9936a"
content_background:                 "#fcc637cc"
hyperlink_color:                    "#8b520c"
hyperlink_hover_color:              "#bd7072"
ratioscore_light:                   "#bfa571"
header_color:                       "#8a7e00"
text_color:                         "#8a7e00"

# General colors
ratioscore_dark:                    "#667780"
ratioscore_light:                   "#bf9471"

# Sidebar colors:
sidebar_background:                 "#fffaed"
sidebar_hyperlink_color:            "#667780"
sidebar_hyperlink_hover_color:      "#fcc637cc"

# Ratioscore toolbar colors:
ratioscore_button_background:       "#b0a6a0"
ratioscore_button_light:            "#ffd000"
ratioscore_button_highlight:        "#fffaed"
ratioscore_button_background_hover: "#ff9752"

# Ratioscore editor colors:
ratioscore_editor_font_color:       "#000000"
ratioscore_editor_background:       "white"


# https://paletton.com/#uid=50t0u0kkzfscZnYgqjboJbEu27m
#
# Main color:  #7b4f2C
# Darker hue:  #3b1c04
#              #5d3515
#              #996d4A
# Lighter hue: #bf9471
#
# Red related colors:
# Main color:  #7a2c2E
# Darker hue:  #3a0405
#              #5c1517
#              #974a4c
# Lighter hue: #bd7072
#
# Yellowish related colors:
# Main color:  #7b602c
# Darker hue:  #3b2804
#              #5d4415
#              #997e4a
# Lighter hue: #bfa571
#


github:
  repo:           https://github.com/craigsapp/ratioscore


exclude:
   - src
   - include
   - scores
   - external
   - tests


